config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_attachments
  resources :post_attachments
  resources :comments
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/profile'
  resources :driverrides do
    resources :commonts
  end
  resources :passengerrides do
    resources :comments
  end

  resources :conversations do
    resources :messages
  end
  resources :requestforpms do
    collection do
      post 'updatestatus'
    end
  end
  resources :requestfordms do
    collection do
      post 'updatestatus'
    end
  end
end

app/models/passengerride.rb
class Passengerride < ApplicationRecord


  belongs_to :user

  has_one :bookforpm

  has_many :requestforpms

  has_many :comments

  has_many :vehicle_attachments
  accepts_nested_attributes_for :vehicle_attachments


  validates :vehicle, presence: true
  validates :seats, presence: true, :numericality => { :greater_than_or_equal_to => 1 }
  validates :model, presence: true
  validates :rent, presence: true, :numericality => { :greater_than_or_equal_to => 1 }
  validates :fuel, presence: true
  validates :mileage, :numericality => { :greater_than_or_equal_to => 1 }, :allow_nil => true

  VEHICLE_LIST = ["Car", "Mini Van", "Bus", "Bike"]
  VEHICLES_LIST = [" ","Car", "Mini Van", "Bus", "Bike"]
  FUEL_LIST = ["Petrol", "Diesel", "CNG"]
  FUELS_LIST = [" ","Petrol", "Diesel", "CNG"]
end

app/controllers/passengerrides_controller.rb
class PassengerridesController < ApplicationController

  before_action :para_passengerride, only: [:edit, :update, :show]
  load_and_authorize_resource :except => :create

  def index
    @q = Passengerride.ransack(params[:q])
    @q.sorts = ['created_at desc'] if @q.sorts.empty?
    @passengerrides = @q.result.paginate(page: params[:page], per_page: 10)
  end

  def new
    @passengerride = Passengerride.new
    @vehicle_attachment = @passengerride.vehicle_attachments.build
  end

  def show
    @vehicle_attachments = @passengerride.vehicle_attachments.all
    @requestforpm = Requestforpm.new(passengerride_id: @passengerride.id)
  end

  def edit
  end

  def create

    @passengerride = Passengerride.new(passengerride_params)
    @passengerride.user = current_user
    if @passengerride.save
      params[:vehicle_attachments]['avatar'].each do |a|
        @vehicle_attachment = @passengerride.vehicle_attachments.create!(:avatar => a)
      end
      flash[:success] = 'Ad was successfully posted.'
      redirect_to passengerride_path(@passengerride)
    else
      render 'new'
    end
  end

  def update

    @passengerride.user = current_user
    if @passengerride.update(passengerride_params)
      flash[:success] = 'Ad was successfully updated'
      redirect_to passengerride_path(@passengerride)
    else
      render 'edit'
    end
  end


  def destroy
    @passengerride = Passengerride.find(params[:id])
    @passengerride.destroy
    flash[:danger] = "Ad has been deleted successfully"
    redirect_to passengerrides_path
  end


  private

  def para_passengerride
    @passengerride = Passengerride.find(params[:id])
  end

  private

  def passengerride_params
    #params[:passengerride][:ac] = params[:passengerride][:ac].join(', ')
    #params[:passengerride][:tv] = params[:passengerride][:tv].join(', ')
    #params[:passengerride][:music] = params[:passengerride][:music].join(', ')
    #params[:passengerride][:auxcable] = params[:passengerride][:auxcable].join(', ')
    #params[:passengerride][:bluetooth] = params[:passengerride][:bluetooth].join(', ')
    #params[:passengerride][:navigation] = params[:passengerride][:navigation].join(', ')
    #params[:passengerride][:rearbackupcamera] = params[:passengerride][:rearbackupcamera].join(', ')
    #params[:passengerride][:pets] = params[:passengerride][:pets].join(', ')
    #params[:passengerride][:drinking] = params[:passengerride][:drinking].join(', ')
    #params[:passengerride][:eating] = params[:passengerride][:eating].join(', ')
    #params[:passengerride][:smoking] = params[:passengerride][:smoking].join(', ')
    #params[:passengerride][:preview] = params[:passengerride][:preview].join(', ')

    params.require(:passengerride).permit(:vehicle, :seats, :model, :rent, :fuel, :mileage, :title, :additionalinfo, :pickup, :userlocation, :ac, :tv, :music, :auxcable, :bluetooth, :navigation, :rearbackupcamera, :pets, :drinking, :eating, :smoking, vehicle_attachments_attributes: [:id, :passengerride_id, :avatar])
  end

end

app/views/passengerrides/edit.html.erb
<h1 align="center"></h1>
<br><br>
<%= render 'form' %>
</div>

app/views/passengerrides/index.html.erb
<script type="text/javascript">

  $(document).ready(function() {

    var outputSpan = $('#spanOutput');
    var sliderElement = $("#slider");

    sliderElement.slider({

      range: true,
      min: 0,
      max: 50000,
      step: 1,
      values: [0, 50000],
      animate: 'slow',

      slide: function(event, ui) {
        outputSpan.html(ui.values[0] + '&#3647' + ' &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' +
            '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' +
            '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' +
            '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' + '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' +
            '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' +
            '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' + '&nbsp&nbsp&nbsp&nbsp&nbsp' + ui.values[1] + '&#3647');
      },
      stop: function(event, ui){
        $('#q_rent_gteq').val(ui.values[0]);
        $('#q_rent_lteq').val(ui.values[1]);
      }
    });
    outputSpan.html(sliderElement.slider('values', 0) + ' &#3647 ' + ' &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' +
        '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' +
        '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' +
        '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' + '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' +
        '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' +
        '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp' + '&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp'
         + sliderElement.slider('values', 1) + '&#3647');
  });

</script>

<h2 align="center">Search for Vehicles</h2>
<br>

<div class="bootstrap-iso">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12">
        <div class="form-horizontal">

          <%= search_form_for @q do |f| %>

              <div class="form-group ">
                <div class="control-label col-sm-2 ">
                  <%= f.label :vehicle_eq, 'Select Vehicle' %>
                </div>
                <div class="col-sm-8">
                  <%= f.select :vehicle_eq, options_for_select( Passengerride::VEHICLES_LIST, @q.vehicle_eq), {}, {:class => 'form-control'} %>
                </div>
              </div>
              <br>
              <div class="form-group ">
                <div class="control-label col-sm-2 ">
                  <p><b>Rent Range</b> </p>
                </div>
                <div class="col-sm-8">
                  <span id="spanOutput"></span>
                  <%= f.hidden_field :rent_gteq, class: 'form-control', placeholder: 'Minimum Rent' %>
                  <%= f.hidden_field :rent_lteq, class: 'form-control', placeholder: 'Maximum Rent' %>
                </div>
                <div class="col-sm-8" align="center">
                  <div id="slider"></div>
                  <br>
                </div>
              </div>




              <div class="form-group ">
                <div class="control-label col-sm-2 ">
                  <%= f.label :fuel_eq, 'Select Fuel' %>
                </div>
                <div class="col-sm-8">
                  <%= f.select :fuel_eq, options_for_select( Passengerride::FUELS_LIST, @q.fuel_eq), {}, {:class => 'form-control'} %>
                </div>
              </div>

              <div class="form-group">
                <div class="col-sm-offset-2 col-sm-8">
                  <div>
                    <%= f.submit 'Search', class: 'btn btn-primary' %>
                  </div>
                </div>
              </div>

          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

<div class="bootstrap-iso">
  <div class="container-fluid">

    <div align="right">
      <%= sort_link @q, :model, "Sort by Model" %> |  <%= sort_link @q, :rent, "Sort by Rent" %> |  <%= sort_link @q, :seats, "Sort by Seats" %>
    </div>

  </div>
</div>

<% if @passengerrides.present? %>


    <% @passengerrides.each do |passengerride| %>
        <div class="well col-xs-14 col-xs-offset">
          <div class="container-fluid">

            <div class="row">

              <div class="col-lg-6"><hr>
                <p>
                  <b>Type of Vehicle</b>: &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= passengerride.vehicle %>
                </p>
                <p>
                  <b>Model</b>: &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= passengerride.model %>
                </p>
                </p>
                <p>
                  <b>Rent</b>: &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&#3647;<%= passengerride.rent %> / Day
                </p>
                <hr>
              </div>

            </div>

            <div class="row">

              <div class="col-lg-6">

                <p><b>Posted by</b> <%= passengerride.user.username %> <%= time_ago_in_words(passengerride.created_at) %> ago</p>

              </div>


            </div>

            <br>


            <div class="row">
              <div class="col-lg-6">
                <div class="passengerride-actions">
                  <% if passengerride.user == current_user %>
                      <%= link_to 'View Details', passengerride_path(passengerride), class: "btn btn-info" %>
                      <% @rangedds = Requestforpm.where('(passengerride_id = ?) AND (status = ?)', passengerride.id, 'Accepted') %>

                      <% if @rangedds.present? %>

                      <% else %>
                          <%= link_to 'Edit', edit_passengerride_path(passengerride), class: "btn btn-success" %>
                          <%= link_to 'Delete', passengerride_path(passengerride), method: :delete,
                                      data: { confirm: "Are you sure you want to delete this ride?"},
                                      class: "btn btn-danger"%>
                      <% end %>
                  <% else %>
                      <%= link_to 'View Details', passengerride_path(passengerride), class: "btn btn-info" %>
                      <%= link_to 'Book', passengerride_path(passengerride), class: "btn btn-primary" %>
                      <%= link_to 'Message', passengerride_path(passengerride), class: "btn btn-warning" %>
                  <% end %>



                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>


<% else %>

    <div class="well col-xs-14 col-xs-offset">
      <div class="container-fluid">
        <div class="row">
          <h4 align="center">Oops, no results found!</h4>
        </div>
      </div>
    </div>
<% end %>

<%= will_paginate @passengerrides, renderer: BootstrapPagination::Rails, previous_label: 'Older', next_label: 'Newer' %>

app/views/passengerrides/new.html.erb
<h1 align="center"></h1>
<br><br>
<%= render 'form' %>
</div>

app/views/passengerrides/show.html.erb
<link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />
<link rel="stylesheet" href="https://formden.com/static/cdn/font-awesome/4.4.0/css/font-awesome.min.css" />
<style>.bootstrap-iso .formden_header h2, .bootstrap-iso .formden_header p, .bootstrap-iso form{font-family: Arial, Helvetica, sans-serif; color: black}.bootstrap-iso form button, .bootstrap-iso form button:hover{color: white !important;} .asteriskField{color: red;}</style>


<br><br>
<% @vehicle_attachments.each do |p| %>
    <%= image_tag p.avatar_url %>
    <%= link_to "Edit Attachment", edit_vehicle_attachment_path(p) %>
<% end %>

<div class="well col-xs-14 col-xs-offset">




  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6">
        <br>

        <h4><i class="fa fa-car"></i> &nbsp<b>Vehicle Details</b></h4>
        <hr><br>
        <p>
          <b>Vehicle Type:</b> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= @passengerride.vehicle %>
        </p>
        <br>
        <p>
          <b>Model:</b> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<%= @passengerride.model %>
        </p>
        <br>
        <p>
          <b>Rent: </b>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&#3647;<%= @passengerride.rent %> / Day
        </p>
      </div>
      <div class="col-lg-6">
        <br>
        <h4><i class="fa fa-location-arrow"></i> &nbsp<b>Pickup Location</b></h4>
        <hr><br>
        <p>
          <b>Address:</b><%= @passengerride.pickup %>
        </p><br>
        <p>
          <% if @passengerride.userlocation == true %>
              <b>Also delivers to user preferred location.</b>
          <% end %>
        </p>
      </div>
    </div>
    <br>
    <hr><br>
    <div class="row">
      <div class="col-lg-6">
        <h4><i class="fa fa-bars"></i> &nbsp<b>Specifications</b></h4>
        <hr>
        <% if @passengerride.ac.present? || @passengerride.navigation.present? || @passengerride.rearbackupcamera.present? || @passengerride.tv.present? || @passengerride.mileage.present? || @passengerride.seats.present? || @passengerride.music.present? %>

            <% if @passengerride.fuel.present? %>
                <p>
                  <i class="fa fa-tint"></i>&nbsp&nbsp&nbsp&nbsp<b> | <%= @passengerride.fuel %></b>
                </p>
                <br>
            <% end %>
            <% if @passengerride.seats.present? %>
                <p>
                  <i class="fa fa-users"></i>&nbsp&nbsp<b> | <%= @passengerride.seats %> Seater</b>
                </p>
                <br>
            <% end %>
            <% if @passengerride.mileage.present? %>
                <p>
                  <i class="fa fa-road"></i> &nbsp<b> | <%= @passengerride.mileage %> kilometres per 1 litre</b>
                </p>
                <br>
            <% end %>
            <% if @passengerride.ac.present? %>
                <p>
                  <i class="fa fa-map-o"></i> &nbsp <b> | Air Conditioner</b>
                </p>
                <br>
            <% end %>
            <% if @passengerride.tv.present? %>
                <p>
                  <i class="fa fa-television"></i> &nbsp<b> | Television</b>
                </p>
                <br>
            <% end %>
            <% if @passengerride.music.present? %>


                <% if @passengerride.bluetooth.present? && @passengerride.auxcable.present? %>
                    <p>
                      <i class="fa fa-music"></i> &nbsp&nbsp<b> | Music System with AUX cable and bluetooth.</b>
                    </p>
                    <br>
                <% elsif @passengerride.bluetooth.present? %>
                    <p>
                      <i class="fa fa-music"></i> &nbsp&nbsp<b> | Music System with bluetooth.</b>
                    </p>
                    <br>
                <% elsif @passengerride.auxcable.present? %>
                    <p>
                      <i class="fa fa-music"></i> &nbsp&nbsp<b> | Music System with AUX cable</b>
                    </p>
                    <br>
                <% else %>
                    <p>
                      <i class="fa fa-music"></i> &nbsp&nbsp<b> | Music System</b>
                    </p>
                    <br>
                <% end %>
            <% end %>
            <% if @passengerride.navigation.present? %>
                <p>
                  <i class="fa fa-map-marker"></i> &nbsp&nbsp&nbsp<b> | Navigation</b>
                </p>
                <br>
            <% end %>
            <% if @passengerride.rearbackupcamera.present? %>
                <p>
                  <i class="fa fa-camera"></i>&nbsp&nbsp<b> | Rear Backup Camera</b>
                </p>
                <br>
            <% end %>


            <hr>
            <br>
        <% end %>
      </div>
      <div class="col-lg-6">
        <h4><i class="fa fa-ban"></i> &nbsp<b>Restrictions</b></h4>
        <hr>
        <% if @passengerride.pets.present? %>
            <p>
              <i class="fa fa-paw"></i>&nbsp&nbsp<b> | Pets are not allowed into the vehicle.</b>
            </p>
            <br>
        <% end %>
        <% if @passengerride.drinking.present? %>
            <p>
              <i class="fa fa-glass"></i>&nbsp&nbsp<b> | Drinking alcohol in the vehicle is prohibited.</b>
            </p>
            <br>
        <% end %>
        <% if @passengerride.smoking.present? %>
            <p>
              <i class="fa fa-magic"></i>&nbsp&nbsp<b> | Smoking in the vehicle is prohibited..</b>
            </p>
            <br>
        <% end %>
        <% if @passengerride.eating.present? %>
            <p>
              <i class="fa fa-birthday-cake"></i>&nbsp&nbsp<b> | Eating in the vehicle is prohibited.</b>
            </p>
            <br>
        <% end %>


      </div>
      <hr>
    </div>

    <div class="row">
      <div class="col-lg-6">
        <% if @passengerride.additionalinfo.present? %>
            <hr>
            <h4><i class="fa fa-info"></i>&nbsp&nbsp&nbsp&nbsp<b>More Info</b></h4>
            <hr>
            <p>
              <%= @passengerride.additionalinfo %>
            </p>
            <br>
        <% end %>

        <div class="passengerride-actions">
          <% if @passengerride.user == current_user %>
              <%= link_to 'Back', passengerrides_path, class: "btn" %>
              <% @rangeddg = Requestforpm.where('(passengerride_id = ?) AND (status = ?)', @passengerride.id, 'Accepted') %>
              <% if @rangeddg.present? %>

              <% else %>
                  <%= link_to 'Edit', edit_passengerride_path(@passengerride), class: "btn btn-success" %>
                  <%= link_to 'Delete', passengerride_path(@passengerride), method: :delete,
                              data: { confirm: "Are you sure you want to delete this ride?"},
                              class: "btn btn-danger"%>
                  <br><br>
              <% end %>
              <br>
              <%= render partial: 'requestforpms/form' %>
          <% else %>
              <%= link_to 'Back', passengerrides_path, class: "btn" %>


              <%#= form_for(@requestforpm) do |fo| %>

              <%#= fo.hidden_field :passengerride_id, :value =>  %>

              <%# end %>

              <%#= link_to 'Add Ride (currently building)', '#', class: "btn btn-primary" %>
              <%= render partial: 'requestforpms/form' %>
          <% end %>


          <%#= render :partial => @passengerride.requestforpms %>
        </div>
      </div>
    </div>
    <!--<div class="col-lg-6">-->
    <!--<b>Place map here</b>-->
    <!--</div>-->
    <hr>
    <div class="row">
      <div class="col-lg-6">

        <h2><%= @passengerride.comments.count %> Comments</h2>
        <br>
        <%= render @passengerride.comments %>
        <br>
        <h3>Add a comment:</h3>
        <%= render 'comments/form' %>
      </div>
    </div>
  </div>
</div>
</div>

<% if @passengerride.user != current_user %>
    <div class="well col-xs-14 col-xs-offset">

      <h4 align="center"> Contact me for any queries!</h4>


      <!--<div class="bootstrap-iso">-->
      <div class="container-fluid">
        <div class="row">
          <div class="col-xs-12">
            <div class="form-horizontal">

              <%= form_tag conversations_path, method: :post do %>
                  <div class="form-group">
                    <div class="col-sm-8">
                      <%= hidden_field_tag :user_id, nil, :value => @passengerride.user.id %>
                      <%#= select_tag :user_id, options_from_collection_for_select(User.all, :id, :name) %>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="col-sm-8">
                      <%= text_field_tag :subject, nil, class: "select form-control", placeholder: "Subject*" %>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="col-sm-8">
                      <%= text_area_tag :body, nil, class: "select form-control", placeholder: "Enter your message here." %>
                    </div>
                  </div>
                  <br>
                  <%= submit_tag 'Send Message', class: 'btn btn-warning' %>

              <% end %>

            </div>
          </div>
        </div>
      </div>
    </div>
    <!--</div>-->
<% end %>

<br>