config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_attachments
  resources :post_attachments
  resources :comments
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/profile'
  resources :driverrides do
    resources :commonts
  end
  resources :passengerrides do
    resources :comments
  end

  resources :conversations do
    resources :messages
  end
  resources :requestforpms do
    collection do
      post 'updatestatus'
    end
  end
  resources :requestfordms do
    collection do
      post 'updatestatus'
    end
  end
end

app/models/vehicle_attachment.rb
class VehicleAttachment < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :passengerride
end

app/controllers/vehicle_attachments_controller.rb
class VehicleAttachmentsController < ApplicationController
  before_action :set_vehicle_attachment, only: [:show, :edit, :update, :destroy]

  # GET /vehicle_attachments
  # GET /vehicle_attachments.json
  def index
    @vehicle_attachments = VehicleAttachment.all
  end

  # GET /vehicle_attachments/1
  # GET /vehicle_attachments/1.json
  def show
  end

  # GET /vehicle_attachments/new
  def new
    @vehicle_attachment = VehicleAttachment.new
  end

  # GET /vehicle_attachments/1/edit
  def edit
  end

  # POST /vehicle_attachments
  # POST /vehicle_attachments.json
  def create
    @vehicle_attachment = VehicleAttachment.new(vehicle_attachment_params)

    respond_to do |format|
      if @vehicle_attachment.save
        format.html { redirect_to @vehicle_attachment, notice: 'Vehicle attachment was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle_attachment }
      else
        format.html { render :new }
        format.json { render json: @vehicle_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_attachments/1
  # PATCH/PUT /vehicle_attachments/1.json
  def update
    respond_to do |format|
      if @vehicle_attachment.update(vehicle_attachment_params)
        format.html { redirect_to @vehicle_attachment.passengerride, notice: 'Post attachment was successfully updated.' }
      end
    end
  end

  # DELETE /vehicle_attachments/1
  # DELETE /vehicle_attachments/1.json
  def destroy
    @vehicle_attachment.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_attachments_url, notice: 'Vehicle attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_attachment
      @vehicle_attachment = VehicleAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_attachment_params
      params.require(:vehicle_attachment).permit(:passengerride_id, :avatar)
    end
end

app/helpers/vehicle_attachments_helper.rb
module VehicleAttachmentsHelper
end

app/views/vehicle_attachments/_form.html.erb
<%= image_tag @vehicle_attachment.avatar %>
<%= form_for(@vehicle_attachment) do |f| %>
    <div class="field">
      <%= f.label :avatar %><br>
      <%= f.file_field :avatar %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/vehicle_attachments/edit.html.erb
<h1>Editing Vehicle Attachment</h1>

<%= render 'form', vehicle_attachment: @vehicle_attachment %>

<%= link_to 'Show', @vehicle_attachment %> |
<%= link_to 'Back', vehicle_attachments_path %>

app/views/vehicle_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicle Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Passengerride</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicle_attachments.each do |vehicle_attachment| %>
      <tr>
        <td><%= vehicle_attachment.passengerride_id %></td>
        <td><%= vehicle_attachment.avatar %></td>
        <td><%= link_to 'Show', vehicle_attachment %></td>
        <td><%= link_to 'Edit', edit_vehicle_attachment_path(vehicle_attachment) %></td>
        <td><%= link_to 'Destroy', vehicle_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle Attachment', new_vehicle_attachment_path %>

app/views/vehicle_attachments/new.html.erb
<h1>New Vehicle Attachment</h1>

<%= render 'form', vehicle_attachment: @vehicle_attachment %>

<%= link_to 'Back', vehicle_attachments_path %>

app/views/vehicle_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Passengerride:</strong>
  <%= @vehicle_attachment.passengerride_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @vehicle_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_vehicle_attachment_path(@vehicle_attachment) %> |
<%= link_to 'Back', vehicle_attachments_path %>