config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_attachments
  resources :post_attachments
  resources :comments
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/profile'
  resources :driverrides do
    resources :commonts
  end
  resources :passengerrides do
    resources :comments
  end

  resources :conversations do
    resources :messages
  end
  resources :requestforpms do
    collection do
      post 'updatestatus'
    end
  end
  resources :requestfordms do
    collection do
      post 'updatestatus'
    end
  end
end

app/models/post_attachment.rb
class PostAttachment < ApplicationRecord

  mount_uploader :avatar, AvatarUploader
  belongs_to :driverride

end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]

  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
  end

  # GET /post_attachments/new
  def new
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = PostAttachment.new(post_attachment_params)

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
    respond_to do |format|
      if @post_attachment.update(post_attachment_params)
        format.html { redirect_to @post_attachment.driverride, notice: 'Post attachment was successfully updated.' }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_attachments_url, notice: 'Post attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:driverride_id, :avatar)
    end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/post_attachments/_form.html.erb
<%= image_tag @post_attachment.avatar %>
<%= form_for(@post_attachment) do |f| %>
    <div class="field">
      <%= f.label :avatar %><br>
      <%= f.file_field :avatar %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/post_attachments/edit.html.erb
<h1>Editing Post Attachment</h1>

<%= render 'form', post_attachment: @post_attachment %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Driverride</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_attachments.each do |post_attachment| %>
      <tr>
        <td><%= post_attachment.driverride_id %></td>
        <td><%= post_attachment.avatar %></td>
        <td><%= link_to 'Show', post_attachment %></td>
        <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></td>
        <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Attachment', new_post_attachment_path %>

app/views/post_attachments/new.html.erb
<h1>New Post Attachment</h1>

<%= render 'form', post_attachment: @post_attachment %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Driverride:</strong>
  <%= @post_attachment.driverride_id %>
</p>

<p>
  <strong>Avatar:</strong>
  <%= @post_attachment.avatar %>
</p>

<%= link_to 'Edit', edit_post_attachment_path(@post_attachment) %> |
<%= link_to 'Back', post_attachments_path %>