config/routes.rb
Rails.application.routes.draw do
  resources :vehicle_attachments
  resources :post_attachments
  resources :comments
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'pages/home'
  get 'pages/about'
  get 'pages/profile'
  resources :driverrides do
    resources :commonts
  end
  resources :passengerrides do
    resources :comments
  end

  resources :conversations do
    resources :messages
  end
  resources :requestforpms do
    collection do
      post 'updatestatus'
    end
  end
  resources :requestfordms do
    collection do
      post 'updatestatus'
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.member?
      can :read, Driverride
      can :create, Driverride
      can :update, Driverride do |driverride|
        driverride.try(:user) == user
      end
      can :destroy, Driverride do |driverride|
        driverride.try(:user) == user
      end
    else
      can :read, Driverride
    end

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.member?
      can :read, Passengerride
      can :create, Passengerride
      can :update, Passengerride do |dassengerride|
        dassengerride.try(:user) == user
      end
      can :destroy, Passengerride do |dassengerride|
        dassengerride.try(:user) == user
      end
    else
      can :read, Passengerride
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookforpm.rb
class Bookforpm < ApplicationRecord

  belongs_to :passengerride
  belongs_to :customer, :class_name => 'User'

  validates_uniqueness_of :passengerride
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :passengerride
end

app/models/commont.rb
class Commont < ApplicationRecord
  belongs_to :driverride
end

app/models/driverride.rb
class Driverride < ActiveRecord::Base


  belongs_to :user

  has_many :requestforpms

  has_many :commonts

  has_many :post_attachments
  accepts_nested_attributes_for :post_attachments

  validates :name, presence: true
  validates :rent, presence: true
  validates :address, presence: true
  validates :contract, presence: true, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 60 }, :allow_nil => true
  validates :area, :numericality => { :greater_than_or_equal_to => 1 }, :allow_nil => true
  validates :bedroom, presence: true, :numericality => { :greater_than_or_equal_to => 1 }, :allow_nil => true
  validates :bathroom, presence: true, :numericality => { :greater_than_or_equal_to => 1 }, :allow_nil => true
  validates :kitchen, presence: true, :numericality => { :greater_than_or_equal_to => 1 }, :allow_nil => true

end

app/models/passengerride.rb
class Passengerride < ApplicationRecord


  belongs_to :user

  has_one :bookforpm

  has_many :requestforpms

  has_many :comments

  has_many :vehicle_attachments
  accepts_nested_attributes_for :vehicle_attachments


  validates :vehicle, presence: true
  validates :seats, presence: true, :numericality => { :greater_than_or_equal_to => 1 }
  validates :model, presence: true
  validates :rent, presence: true, :numericality => { :greater_than_or_equal_to => 1 }
  validates :fuel, presence: true
  validates :mileage, :numericality => { :greater_than_or_equal_to => 1 }, :allow_nil => true

  VEHICLE_LIST = ["Car", "Mini Van", "Bus", "Bike"]
  VEHICLES_LIST = [" ","Car", "Mini Van", "Bus", "Bike"]
  FUEL_LIST = ["Petrol", "Diesel", "CNG"]
  FUELS_LIST = [" ","Petrol", "Diesel", "CNG"]
end

app/models/post_attachment.rb
class PostAttachment < ApplicationRecord

  mount_uploader :avatar, AvatarUploader
  belongs_to :driverride

end

app/models/requestfordm.rb
class Requestfordm < ApplicationRecord

  belongs_to :driverride
  belongs_to :customer, :class_name => 'User'

end

app/models/requestforpm.rb
class Requestforpm < ApplicationRecord

  belongs_to :passengerride
  belongs_to :customer, :class_name => 'User'

end

app/models/role.rb
class Role < ApplicationRecord

  has_many :users

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates_uniqueness_of :username
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validates_presence_of :username
  validates_uniqueness_of :email
  validates_presence_of :password

  belongs_to :role
  has_many :driverrides
  has_many :passengerrides

  has_many :customers, through: :bookforpms

  has_many :customers, through: :requestforpms

  has_many :customers, through: :requestfordms


  acts_as_messageable

  before_validation :assign_role

  def assign_role
    self.role = Role.find_by_name("Member") if self.role.nil?
  end

  def admin?
    self.role.name == "Admin" if !self.role.blank?
  end
  def member?
    self.role.name == "Member" if !self.role.blank?
  end

  def name
    "#{email}"
  end

  def mailboxer_email(object)
    nil
  end

end

app/models/vehicle_attachment.rb
class VehicleAttachment < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  belongs_to :passengerride
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def profile
    @passengerrides = Passengerride.all
    @driverrides = Driverride.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/commonts_helper.rb
module CommontsHelper
end

app/helpers/driverride_helper.rb
module DriverrideHelper
end

app/helpers/requestfordm_helper.rb
module RequestfordmHelper
end

app/helpers/requestforpms_helper.rb
module RequestforpmsHelper
end

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy; <a href="web11.cs.ait.ac.th">MyTravel</a>
    </small>
    <nav>
      <ul>
        <li><%= link_to "About", pages_about_path%></li>
        <li><%= link_to "Contact Us", "#" %></li>
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, message| %>
        <div class='alert alert-<%= "#{name}" %>'>
          <a href="#" class="close" data-dismiss="alert">&#10006;</a>
          <%= content_tag :div, message, :id => "flash_#{name}" if message.is_a?(String)%>
        </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MyTravel", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>

        <li><%= link_to "Condo", new_driverride_path %></li>
        <li><%= link_to "Vehicle", new_passengerride_path %></li>

        <li><%= link_to "Rent a Place", driverrides_path %></li>
        <li><%= link_to "Rent a Vehicle", passengerrides_path %></li>

        <li><%= link_to "My Inbox", conversations_path %></li>


      </ul>
      <!--<form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
            <li><%= link_to "My Profile", pages_profile_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-primary' %></li>
        <% else %>

            <li><%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-info' %></li>
            <li><%= link_to "Login", new_user_session_path, class: 'btn btn-info' %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Travel</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/navbar' %>
<%= render 'layouts/messages' %>

<div class="container">
  <%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(obj.errors.count, "error") %>
            </h2>
            <div class="panel-body">
              <ul>
                <% obj.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
<% end %>